import pino from "pino";

export const loggerRedactPaths = [
  "req.headers.authorization",
  "req.headers.cookie",
  "req.headers.x-auth-token",
  "req.headers.x-internal-secret",
  "req.headers.x-journal-secret",
  "req.headers.x-shipmastr-courier-key",
  "req.headers.x-shipmastr-signature",
  "req.headers.x-shipmastr-task-secret",
  "req.headers.forwarded",
  "req.headers.x-forwarded-for",
  "req.headers.x-shipmastr-rate-limit-probe-token",
  "req.headers['forwarded']",
  "req.headers['x-forwarded-for']",
  "req.headers['x-internal-secret']",
  "req.headers['x-journal-secret']",
  "req.headers['x-shipmastr-courier-key']",
  "req.headers['x-shipmastr-signature']",
  "req.headers['x-shipmastr-task-secret']",
  "req.headers['x-shipmastr-rate-limit-probe-token']",
  "req.headers.x-shipmastr-intake-signature",
  "req.headers.idempotency-key",
  "req.headers['x-shipmastr-intake-signature']",
  "req.headers['idempotency-key']",
  "req.ip",
  "req.ips",
  "req.remoteAddress",
  "req.socket.remoteAddress",
  "req.connection.remoteAddress",
  "req.client.remoteAddress",
  "res.headers.authorization",
  "*.password",
  "*.passwordHash",
  "*.access_key",
  "*.accessKey",
  "*.authorization",
  "*.bearer",
  "*.pan",
  "*.panEncrypted",
  "*.panIv",
  "*.panAuthTag",
  "*.apiKey",
  "*.token",
  "*.clientSecret",
  "*.webhookSecret",
  "*.credentials",
  "*.secret",
  "*.secretRef",
  "body.password",
  "body.pan",
  "body.credentials",
  "payload.pan",
  "payload.credentials"
];

export const logger = pino({
  level: process.env.NODE_ENV === "production" ? "info" : "debug",
  redact: {
    paths: loggerRedactPaths,
    censor: "[redacted]"
  }
});
