substitutions:
  _IMAGE: asia-south1-docker.pkg.dev/shipmastr-core-prod/shipmastr/shipmastr-api-migrate-status:manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.migrate-status
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
