services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shipmastr
    ports:
      - "5432:5432"
    volumes:
      - shipmastr_pg:/var/lib/postgresql/data

volumes:
  shipmastr_pg:
