export const PLATFORM_READ_ERRORS = {
  CONNECTION_NOT_FOUND: "PLATFORM_CONNECTION_NOT_FOUND",
  CONNECTION_NOT_READY: "PLATFORM_READ_CONNECTION_NOT_READY",
  UNSUPPORTED_PLATFORM: "PLATFORM_READ_UNSUPPORTED_PLATFORM",
  CREDENTIAL_NOT_FOUND: "PLATFORM_CREDENTIAL_NOT_FOUND",
  CREDENTIAL_INACTIVE: "PLATFORM_READ_CREDENTIAL_INACTIVE",
  CREDENTIAL_PLATFORM_MISMATCH: "PLATFORM_READ_CREDENTIAL_PLATFORM_MISMATCH",
  CREDENTIAL_SECRET_MISSING: "PLATFORM_READ_CREDENTIAL_SECRET_MISSING",
  CLIENT_NOT_CONFIGURED: "PLATFORM_READ_CLIENT_NOT_CONFIGURED",
  REQUEST_FAILED: "PLATFORM_READ_REQUEST_FAILED",
  MUTATION_BLOCKED: "PLATFORM_READ_MUTATION_BLOCKED"
} as const;
