import dotenv from "dotenv";
import { z } from "zod";

dotenv.config();

const envBoolean = (defaultValue: boolean) => z.preprocess((value) => {
  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (["true", "1", "yes", "on"].includes(normalized)) return true;
    if (["false", "0", "no", "off", ""].includes(normalized)) return false;
  }
  return value;
}, z.boolean().default(defaultValue));

const schema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  APP_ENV: z.enum(["development", "test", "staging", "production"]).default("production"),
  PORT: z.coerce.number().default(8080),
  DATABASE_URL: z.string().min(1),
  JWT_SECRET: z.string().min(32),
  APP_SECRET_PEPPER: z.string().min(16),
  WEBHOOK_SECRET: z.string().min(32),
  SHIPMASTR_INTERNAL_SECRET: z.string().min(32).optional(),
  CORS_ORIGINS: z.string().default(""),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().optional(),
  SMTP_SECURE: z.coerce.boolean().default(true),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  SMTP_FROM: z.string().optional(),
  SMTP_REPLY_TO: z.string().optional(),
  ADMIN_EMAIL: z.string().email().optional(),
  JOURNAL_EMAIL_PROVIDER: z.enum(["smtp", "mock", "webhook", "not_configured"]).default("not_configured"),
  JOURNAL_EMAIL_LIVE_SEND: z.coerce.boolean().default(false),
  JOURNAL_AUTOPUBLISH_STORE: z.enum(["postgres", "db", "not_configured"]).default("not_configured"),
  JOURNAL_EMAIL_FROM: z.string().optional(),
  EMAIL_FROM: z.string().email().optional(),
  EMAIL_FROM_NAME: z.string().optional(),
  DOMAIN_EMAIL_FROM_NAME: z.string().default("Shipmastr"),
  DOMAIN_EMAIL_FROM_ADDRESS: z.string().email().default("noreply@shipmastr.com"),
  NEWSLETTER_SECRET: z.string().optional(),
  JOURNAL_ADMIN_TOKEN: z.string().optional(),
  EMAIL_SPF_VERIFIED: z.coerce.boolean().default(false),
  EMAIL_DKIM_VERIFIED: z.coerce.boolean().default(false),
  EMAIL_DMARC_VERIFIED: z.coerce.boolean().default(false),
  EMAIL_DKIM_SELECTORS: z.string().default("google,default,selector1,selector2,resend"),
  GCP_PROJECT_ID: z.string().optional(),
  CLOUD_TASKS_LOCATION: z.string().default("asia-south1"),
  EMAIL_QUEUE_NAME: z.string().default("shipmastr-email-queue"),
  TASK_HANDLER_URL: z.string().url().optional(),
  N8N_AUTOPILOT_ENABLED: z.coerce.boolean().default(false),
  N8N_AUTOPILOT_DISPATCH_URL: z.string().url().optional(),
  N8N_AUTOPILOT_WORKFLOW_URLS: z.string().optional(),
  N8N_AUTOPILOT_SIGNING_SECRET: z.string().min(32).optional(),
  N8N_AUTOPILOT_TIMEOUT_MS: z.coerce.number().int().min(1000).max(30000).default(8000),
  SHIPMASTR_AUTOMATION_SMOKE_CALLBACKS_ENABLED: envBoolean(false),
  RESELLERCLUB_BASE_URL: z.string().url().optional(),
  RESELLERCLUB_AUTH_USERID: z.string().optional(),
  RESELLERCLUB_API_KEY: z.string().optional(),
  RESELLERCLUB_CUSTOMER_ID: z.string().optional(),
  RESELLERCLUB_REG_CONTACT_ID: z.string().optional(),
  RESELLERCLUB_ADMIN_CONTACT_ID: z.string().optional(),
  RESELLERCLUB_TECH_CONTACT_ID: z.string().optional(),
  RESELLERCLUB_BILLING_CONTACT_ID: z.string().optional(),
  RESELLERCLUB_IN_NAMESERVER_PARAMS_VERIFIED: envBoolean(false),
  CLOUDFLARE_AUTH_MODE: z.enum(["api_token", "global_key"]).default("api_token"),
  CLOUDFLARE_AUTH_EMAIL: z.string().optional(),
  CLOUDFLARE_GLOBAL_API_KEY: z.string().optional(),
  CLOUDFLARE_API_TOKEN: z.string().optional(),
  CLOUDFLARE_ZONE_ID: z.string().optional(),
  CLOUDFLARE_CUSTOM_METADATA_ENABLED: envBoolean(false),
  ALLOW_CLOUDFLARE_ADMIN_MUTATIONS: envBoolean(false),
  ALLOW_APEX_DOMAIN_AUTOMATION: envBoolean(false),
  SHIPMASTR_INTERNAL_PROVISIONING_SECRET: z.string().min(16).optional(),
  SHIPMASTR_DOMAIN_PROVIDER_MODE: z.enum(["mock", "sandbox", "live"]).default("mock"),
  ALLOW_RESELLERCLUB_AVAILABILITY_CHECK: envBoolean(false),
  RESELLERCLUB_DEBUG_SAFE: envBoolean(false),
  ALLOW_RESELLERCLUB_BASE_MATRIX: envBoolean(false),
  ALLOW_LIVE_DOMAIN_REGISTRATION: envBoolean(false),
  COMM_PROVIDER: z.enum(["mock", "whatsapp", "sms"]).default("mock"),
  WHATSAPP_PROVIDER: z.enum(["mock", "gupshup", "interakt", "wati", "aisensy"]).default("mock"),
  WHATSAPP_PROVIDER_WEBHOOK_SECRET: z.string().min(16).optional(),
  SMS_PROVIDER: z.enum(["mock", "msg91", "twilio"]).default("mock"),
  CARRIER_PROVIDER: z.enum(["manual", "mock"]).default("manual"),
  CARRIER_API_BASE_URL: z.string().optional(),
  CARRIER_API_KEY_SECRET_NAME: z.string().optional(),
  CARRIER_ACCOUNT_ID_SECRET_NAME: z.string().optional(),
  CARRIER_WEBHOOK_SECRET_NAME: z.string().optional(),
  BIGSHIP_MODE: z.enum(["mock", "sandbox", "live"]).default("mock"),
  BIGSHIP_BASE_URL: z.string().url().default("https://api.bigship.direct/"),
  BIGSHIP_API_KEY: z.string().optional(),
  BIGSHIP_CLIENT_ID: z.string().optional(),
  BIGSHIP_CLIENT_SECRET: z.string().optional(),
  BIGSHIP_USERNAME: z.string().optional(),
  BIGSHIP_PASSWORD: z.string().optional(),
  BIGSHIP_ACCESS_KEY: z.string().optional(),
  BIGSHIP_TIMEOUT_MS: z.coerce.number().int().positive().default(15000),
  BIGSHIP_ENABLE_REAL_CALLS: envBoolean(false),
  BIGSHIP_ENABLED: envBoolean(false),
  BIGSHIP_MOCK_MODE: envBoolean(true),
  SHIPMASTR_CREDENTIAL_VAULT_KEY: z.string().optional(),
  CREDENTIAL_VAULT_PROVIDER: z.enum([
    "LOCAL_MOCK",
    "LOCAL_ENCRYPTED",
    "ENV_ENCRYPTION_KEY",
    "KMS_PLACEHOLDER",
    "KMS_INTERFACE"
  ]).default("LOCAL_MOCK"),
  CREDENTIAL_VAULT_KMS_KEY_ID: z.string().optional(),
  CREDENTIAL_VAULT_ENCRYPTION_KEY: z.string().optional(),
  CREDENTIAL_VAULT_ROTATION_ENABLED: envBoolean(false),
  CREDENTIAL_VAULT_REQUIRE_LIVE_FOR_PILOT: envBoolean(true),
  CREDENTIAL_VAULT_ALLOW_LOCAL_MOCK_FOR_PILOT: envBoolean(false),
  PLATFORM_INTEGRATIONS_ENABLE_REAL_READS: envBoolean(false),
  SHIPMASTR_LIVE_MERCHANT_ALLOWLIST: z.string().default(""),
  SHIPMASTR_PILOT_MERCHANT_ID: z.string().optional(),
  LIVE_KMS_PROVIDER_APPROVED: envBoolean(false),
  LIVE_COURIER_PROVIDER_APPROVED: envBoolean(false),
  LIVE_EMAIL_PROVIDER_APPROVED: envBoolean(false),
  LIVE_WEBHOOK_REGISTRATION_APPROVED: envBoolean(false),
  LIVE_PLATFORM_WRITE_APPROVED: envBoolean(false),
  PRODUCTION_DEPLOY_APPROVED: envBoolean(false),
  SHIPMASTR_EMAIL_ENABLED: envBoolean(false),
  SHIPMASTR_EMAIL_MODE: z.enum(["SANDBOX", "LIVE"]).default("SANDBOX"),
  SHIPMASTR_EMAIL_PROVIDER: z.enum(["LOCAL_LOG", "SMTP_SANDBOX", "MOCK"]).default("LOCAL_LOG"),
  SHIPMASTR_EMAIL_PILOT_ONLY: envBoolean(true),
  SHIPMASTR_WEBHOOK_REGISTRATION_ENABLED: envBoolean(false),
  SHIPMASTR_WEBHOOK_REGISTRATION_MODE: z.enum(["DRY_RUN", "LIVE"]).default("DRY_RUN"),
  SHIPMASTR_WEBHOOK_REGISTRATION_PILOT_ONLY: envBoolean(true),
  PUBLIC_WEBHOOK_BASE_URL: z.string().url().optional(),
  SHIPMASTR_LIVE_COURIER_RATES_ENABLED: envBoolean(false),
  SHIPMASTR_LIVE_COURIER_RATES_MODE: z.enum(["DRY_RUN", "LIVE"]).default("DRY_RUN"),
  SHIPMASTR_LIVE_COURIER_RATES_PILOT_ONLY: envBoolean(true),
  SHIPMASTR_LIVE_AWB_LABEL_ENABLED: envBoolean(false),
  SHIPMASTR_LIVE_AWB_LABEL_MODE: z.enum(["DRY_RUN", "LIVE"]).default("DRY_RUN"),
  SHIPMASTR_LIVE_AWB_LABEL_PILOT_ONLY: envBoolean(true),
  SHIPMASTR_ENABLE_LIVE_SHIPROCKET_AWB: envBoolean(false),
  SHIPMASTR_LIVE_SHIPROCKET_ALLOWED_MERCHANT_ID: z.string().optional(),
  SHIPMASTR_LIVE_SHIPROCKET_ALLOWED_SHIPMENT_ID: z.string().optional(),
  SHIPMASTR_LIVE_SHIPROCKET_ONE_SHOT_TOKEN: z.string().optional(),
  SHIPROCKET_BASE_URL: z.string().url().default("https://apiv2.shiprocket.in/"),
  SHIPROCKET_LIVE_CREDENTIALS: z.string().optional(),
  SHIPMASTR_PLATFORM_TRACKING_SYNC_ENABLED: envBoolean(false),
  SHIPMASTR_PLATFORM_TRACKING_SYNC_MODE: z.enum(["DRY_RUN", "LIVE"]).default("DRY_RUN"),
  SHIPMASTR_PLATFORM_TRACKING_SYNC_PILOT_ONLY: envBoolean(true),
  SHIPMASTR_WORKERS_ENABLED: envBoolean(false),
  SHIPMASTR_IMPORT_WORKER_ENABLED: envBoolean(false),
  SHIPMASTR_WEBHOOK_WORKER_ENABLED: envBoolean(false),
  SHIPMASTR_NOTIFICATION_WORKER_ENABLED: envBoolean(false),
  SHIPMASTR_RETRY_WORKER_ENABLED: envBoolean(false),
  SHIPMASTR_WORKER_MAX_BATCH: z.coerce.number().int().min(1).max(100).default(25),
  SHIPMASTR_WORKER_LOCK_SECONDS: z.coerce.number().int().min(30).max(3600).default(300),
  SHIPMASTR_WORKER_DRY_RUN: envBoolean(true),
  GOOGLE_ADDRESS_AUTOCOMPLETE_ENABLED: envBoolean(false),
  GOOGLE_PICKUP_GEOCODING_ENABLED: envBoolean(false),
  GOOGLE_MAP_UI_ENABLED: envBoolean(false),
  GOOGLE_PICKUP_PIN_CONFIRMATION_ENABLED: envBoolean(false),
  GOOGLE_PLACE_DETAILS_ENABLED: envBoolean(false),
  GOOGLE_ADDRESS_VALIDATION_ENABLED: envBoolean(false),
  GOOGLE_ROUTES_ENABLED: envBoolean(false),
  GOOGLE_MAP_TILES_ENABLED: envBoolean(false),
  GOOGLE_GEOCODING_API_KEY: z.string().optional(),
  GOOGLE_GEOCODING_MONTHLY_SOFT_CAP: z.coerce.number().int().min(0).default(5000),
  GOOGLE_GEOCODING_MONTHLY_HARD_CAP: z.coerce.number().int().min(0).default(7000),
  ADDRESS_GEOCODE_QUEUE_NAME: z.string().default("shipmastr-address-geocode-queue"),
  ADDRESS_GEOCODE_TASK_HANDLER_URL: z.string().url().optional(),
  GROWTH_NETWORK_ENABLED: envBoolean(false),
  GROWTH_NETWORK_AUDIENCE: z.enum(["MERCHANT_SELLER_ONLY"]).default("MERCHANT_SELLER_ONLY"),
  GROWTH_NETWORK_EXTERNAL_ADS_ENABLED: envBoolean(false),
  GROWTH_NETWORK_BILLING_ENABLED: envBoolean(false),
  GROWTH_NETWORK_PARTNER_ROUTING_ENABLED: envBoolean(false),
  GROWTH_NETWORK_MESSAGING_ENABLED: envBoolean(false),
  GROWTH_NETWORK_PAYMENT_ENABLED: envBoolean(false),
  GROWTH_NETWORK_BUYER_EXPORT_ENABLED: envBoolean(false),
  GROWTH_NETWORK_PUBLIC_TRACKING_ENABLED: envBoolean(false)
});

export const env = schema.parse(process.env);

export const corsOrigins = env.CORS_ORIGINS
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);

const defaultCorsOrigins = [
  "https://shipmastr.com",
  "https://www.shipmastr.com",
  "https://shipmastr.in",
  "https://www.shipmastr.in"
];

export const allowedCorsOrigins = Array.from(new Set([...corsOrigins, ...defaultCorsOrigins]));
