export type ShippingOrderValidationStatus = "ready_to_ship" | "needs_attention";

export type ShippingOrderSource =
  | "manual"
  | "csv"
  | "api"
  | "storefront"
  | "shopify_import";

export const NEEDS_ATTENTION_REASONS = {
  ADDRESS_QUALITY_LOW: "ADDRESS_QUALITY_LOW",
  MISSING_PHONE: "MISSING_PHONE",
  INVALID_PHONE: "INVALID_PHONE",
  MISSING_PINCODE: "MISSING_PINCODE",
  INVALID_PINCODE: "INVALID_PINCODE",
  MISSING_PACKAGE_WEIGHT: "MISSING_PACKAGE_WEIGHT",
  ZERO_PACKAGE_WEIGHT: "ZERO_PACKAGE_WEIGHT",
  MISSING_BUYER_NAME: "MISSING_BUYER_NAME",
  MISSING_PICKUP_LOCATION: "MISSING_PICKUP_LOCATION",
  COD_AMOUNT_OVER_LIMIT: "COD_AMOUNT_OVER_LIMIT",
  DUPLICATE_ORDER_ID: "DUPLICATE_ORDER_ID"
} as const;

export type NeedsAttentionReason =
  typeof NEEDS_ATTENTION_REASONS[keyof typeof NEEDS_ATTENTION_REASONS];

export const ADDRESS_FLAGS = {
  PINCODE_INVALID_FORMAT: "PINCODE_INVALID_FORMAT",
  ADDRESS_TOO_SHORT: "ADDRESS_TOO_SHORT",
  ADDRESS_LOOKS_TEST: "ADDRESS_LOOKS_TEST",
  STATE_MISSING: "STATE_MISSING",
  CITY_MISSING: "CITY_MISSING",
  LANDMARK_HELPFUL: "LANDMARK_HELPFUL"
} as const;

export const COD_HIGH_VALUE_THRESHOLD_PAISE = 1_000_000;
