const STATE_MAP: Record<string, string> = {
  ap: "Andhra Pradesh",
  andhra: "Andhra Pradesh",
  "andhra pradesh": "Andhra Pradesh",
  ar: "Arunachal Pradesh",
  as: "Assam",
  br: "Bihar",
  cg: "Chhattisgarh",
  chattisgarh: "Chhattisgarh",
  chhattisgarh: "Chhattisgarh",
  ga: "Goa",
  gj: "Gujarat",
  gujarat: "Gujarat",
  hr: "Haryana",
  haryana: "Haryana",
  hp: "Himachal Pradesh",
  jk: "Jammu & Kashmir",
  "j&k": "Jammu & Kashmir",
  jh: "Jharkhand",
  ka: "Karnataka",
  karnataka: "Karnataka",
  kl: "Kerala",
  mp: "Madhya Pradesh",
  "madhya pradesh": "Madhya Pradesh",
  mh: "Maharashtra",
  maharashtra: "Maharashtra",
  mn: "Manipur",
  ml: "Meghalaya",
  mz: "Mizoram",
  nl: "Nagaland",
  od: "Odisha",
  or: "Odisha",
  orissa: "Odisha",
  pb: "Punjab",
  punjab: "Punjab",
  rj: "Rajasthan",
  rajasthan: "Rajasthan",
  sk: "Sikkim",
  tn: "Tamil Nadu",
  "tamil nadu": "Tamil Nadu",
  tg: "Telangana",
  telangana: "Telangana",
  tr: "Tripura",
  up: "Uttar Pradesh",
  "uttar pradesh": "Uttar Pradesh",
  uk: "Uttarakhand",
  uttarakhand: "Uttarakhand",
  uttaranchal: "Uttarakhand",
  wb: "West Bengal",
  "west bengal": "West Bengal",
  dl: "Delhi",
  delhi: "Delhi",
  ch: "Chandigarh",
  dd: "Daman & Diu",
  dn: "Dadra & Nagar Haveli",
  la: "Ladakh",
  ld: "Lakshadweep",
  py: "Puducherry",
  pondicherry: "Puducherry"
};

export function normalizeStateName(raw: string | null | undefined): string {
  const trimmed = String(raw ?? "").trim();
  const key = trimmed.toLowerCase();
  return STATE_MAP[key] ?? trimmed;
}
