-- Align the current Prisma User.role model with the refined actor-role enum
-- created by earlier migrations. This is additive: it only widens accepted
-- role values and updates the default to the schema default.

ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPPORT_STAFF';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MERCHANT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'EXTERNAL_MERCHANT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'EXTERNAL_COURIER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SELLER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COURIER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SELLER_OWNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SELLER_STAFF';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COURIER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COURIER_OPS';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'OWNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'STAFF';
